version: '3.8'

services:
  proxy:
    image: ba
    container_name: ba
    restart: unless-stopped
    volumes:
      - "./data:/dataset"
      - "${PWD}/config.ini:/var/src/config.ini"
      - "${PWD}/info-svm.log:/var/src/info-svm.log"
      - "${PWD}/info-gmm.log:/var/src/info-gmm.log"
      - "${PWD}/info-gmmubm.log:/var/src/info-gmmubm.log"