version: '3'
services:
  sv:
    build:
      context: /home/user/gitprojects/bachelorthesis
      args:
        - GIT_PULL
      dockerfile: /home/user/gitprojects/bachelorthesis/docker/svm/Dockerfile
    container_name: ba
    restart: unless-stopped
    volumes:
      - "./data:/dataset"
      - "${PWD}/config.ini:/var/src/config.ini"
      - "${PWD}/info-svm.log:/var/src/info-svm.log"
      - "${PWD}/info-gmm.log:/var/src/info-gmm.log"
      - "${PWD}/info-gmmubm.log:/var/src/info-gmmubm.log"