name: bachelorthesis
channels:

dependencies:
  - python=3.9
  - librosa=0.8.1
  - matplotlib=3.4.2
  - numpy=1.19.5
  - pandas=1.2.4
  - playsound=1.2.2
  - python_speech_features=0.6
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - SpeechRecognition=3.8.1
  - sounddevice=0.4.1

